version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: lms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'  
    volumes: 
     - ./dockervolume:/var/lib/mysql
    ports:
     - "6033:3306"

  spring-myql-dockercompose:
    restart: on-failure
    container_name: spring-myql-dockercompose
    build: ../
    image: spring-core-api
    expose:
      - "8089"
    ports:
      - "8089:8089"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
